import { StyleSheet, Platform } from 'react-native';

export const getStyles = (COLORS) => StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  topHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 25, paddingTop: 15, paddingBottom: 20 },
  headerProfile: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  brandText: { color: COLORS.textMain, fontSize: 18, fontWeight: '800', letterSpacing: 1.5 },
  headerIcons: { flexDirection: 'row', alignItems: 'center' },
  pageTitle: { color: COLORS.textMain, fontSize: 32, fontWeight: '900', letterSpacing: -0.5 },
  
  headerTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  headerLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 13, fontFamily: Platform.OS === 'ios' ? 'Inter-Medium' : 'sans-serif-medium' },
  visibilityToggle: { marginLeft: 8, padding: 4 },
  headerValue: { color: '#FFFFFF', fontSize: 32, fontWeight: '700', letterSpacing: -0.5 },

  headerTabSwitcher: { flexDirection: 'row', backgroundColor: '#16161A', borderRadius: 12, padding: 4, width: '65%' },
  headerTab: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  headerTabActive: { backgroundColor: '#2A2A35' },
  headerTabText: { color: '#8A8A9A', fontWeight: '700', fontSize: 13 },
  headerTabTextActive: { color: '#FFFFFF' },
  
  performanceContainer: { marginBottom: 25 },
  perfLabel: { color: COLORS.textSub, fontSize: 12, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 5 },
  perfValue: { color: COLORS.textMain, fontSize: 42, fontWeight: '900', letterSpacing: -1.5, marginBottom: 20 },
  timeFiltersBg: { flexDirection: 'row', backgroundColor: COLORS.surfaceHigh, padding: 4, borderRadius: 20, alignSelf: 'flex-start', marginBottom: 20 },
  timeFilterBtn: { paddingVertical: 6, paddingHorizontal: 16, borderRadius: 16 },
  timeFilterActive: { backgroundColor: COLORS.primary },
  timeFilterText: { color: COLORS.textSub, fontSize: 12, fontWeight: 'bold' },
  timeFilterTextActive: { color: COLORS.bg, fontWeight: '900' },
  
  chartBox: { backgroundColor: COLORS.chartBg, borderRadius: 24, justifyContent: 'flex-end', overflow: 'hidden', position: 'relative' },
  tooltipContainer: { position: 'absolute', backgroundColor: COLORS.surfaceHigh, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: COLORS.border, zIndex: 20, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3 },
  tooltipValue: { color: COLORS.textMain, fontSize: 12, fontWeight: '900' },

  trendingGrid: { flexDirection: 'row', gap: 15, marginBottom: 30 },
  trendCard: { flex: 1, backgroundColor: COLORS.surfaceHigh, padding: 15, borderRadius: 16 },
  trendLabel: { color: COLORS.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1, marginBottom: 5 },
  trendValue: { color: COLORS.textMain, fontSize: 20, fontWeight: '900' },
  categoryTitle: { color: COLORS.textSub, fontSize: 12, fontWeight: '700', letterSpacing: 2, textTransform: 'uppercase', paddingHorizontal: 20, paddingVertical: 12, marginTop: 8 },
  compactCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'transparent', paddingVertical: 16, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  compactLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  compactIconBox: { width: 40, height: 40, borderRadius: 10, backgroundColor: COLORS.surfaceHigh, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  compactName: { color: COLORS.textMain, fontSize: 16, fontWeight: '700' },
  compactSub: { color: COLORS.textSub, fontSize: 12, marginTop: 2 },
  compactRight: { alignItems: 'flex-end', marginLeft: 10 },
  compactPrice: { color: COLORS.textMain, fontSize: 16, fontWeight: '700' },
  compactPct: { fontSize: 13, fontWeight: '600', marginTop: 2 },

  dragHandleContainer: { width: '100%', alignItems: 'center', paddingTop: 15, paddingBottom: 20 },
  dragHandle: { width: 40, height: 4, backgroundColor: COLORS.textSub, borderRadius: 2, opacity: 0.5 },
  modalOverlayFlexEnd: { flex: 1, backgroundColor: 'transparent', justifyContent: 'flex-end' },
  
  donutContainer: { alignItems: 'center', justifyContent: 'center', position: 'relative', marginVertical: 5 },
  donutCenterTextContainer: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  donutCenterLabel: { color: COLORS.textSub, fontSize: 12, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 2 },
  donutCenterValue: { color: COLORS.textMain, fontSize: 22, fontWeight: '900', letterSpacing: -0.5 },
  donutCenterPct: { fontSize: 14, fontWeight: 'bold', marginTop: 2 },
  legendContainer: { marginTop: 10, paddingHorizontal: 10 },
  legendItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  legendItemActive: { backgroundColor: COLORS.surfaceHigh, borderRadius: 12, paddingHorizontal: 10, borderBottomWidth: 0, marginVertical: 4 },
  legendColorBox: { width: 12, height: 12, borderRadius: 4, marginRight: 12 },
  legendSymbol: { color: COLORS.textMain, fontSize: 14, fontWeight: 'bold' },
  legendName: { color: COLORS.textSub, fontSize: 11, marginTop: 2 },
  legendPct: { color: COLORS.textMain, fontSize: 16, fontWeight: '900' },

  perfSectionTitle: { color: COLORS.textSub, fontSize: 14, fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 1 },
  perfCard: { backgroundColor: COLORS.surfaceHigh, borderRadius: 16, padding: 15 },
  perfListItem: { marginBottom: 15 },
  perfListHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  perfItemName: { color: COLORS.textMain, fontSize: 15, fontWeight: 'bold' },
  perfItemPct: { fontSize: 14, fontWeight: '900' },


  detailPageBox: { backgroundColor: COLORS.surfaceHigh, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 25, paddingBottom: 50, minHeight: '98%', maxHeight: '98%', zIndex: 2, borderTopWidth: 1, borderTopColor: COLORS.border },
  detailHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 25 },
  detailIconBox: { width: 60, height: 60, borderRadius: 16, backgroundColor: COLORS.surfaceHigh, justifyContent: 'center', alignItems: 'center' },
  detailName: { color: COLORS.textMain, fontSize: 24, fontWeight: '900' },
  detailType: { color: COLORS.textSub, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1, marginTop: 4 },
  detailChartBox: { height: 120, backgroundColor: COLORS.chartBg, borderRadius: 20, padding: 20, justifyContent: 'space-between', overflow: 'hidden', marginBottom: 25 },
  detailCurrentPrice: { color: COLORS.textMain, fontSize: 32, fontWeight: '900', zIndex: 10 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 15, marginBottom: 25 },
  statBox: { flexBasis: '47%', backgroundColor: COLORS.surfaceHigh, padding: 15, borderRadius: 16 },
  statBoxLabel: { color: COLORS.textSub, fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 5 },
  statBoxValue: { color: COLORS.textMain, fontSize: 18, fontWeight: '900' },
  detailNoteArea: { backgroundColor: COLORS.primarySoft, padding: 15, borderRadius: 12, flexDirection: 'row', alignItems: 'center', marginBottom: 25, borderWidth: 1, borderColor: COLORS.primarySoft },
  detailNoteText: { color: COLORS.primaryDim, fontSize: 13, fontStyle: 'italic', flex: 1, fontWeight: '500' },
  detailActionRow: { flexDirection: 'row', gap: 15 },
  detailBtnSecondary: { flex: 1, flexDirection: 'row', backgroundColor: COLORS.surfaceHigh, padding: 16, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  detailBtnSecondaryText: { color: COLORS.textMain, fontSize: 14, fontWeight: 'bold' },
  detailBtnPrimary: { flex: 1, flexDirection: 'row', backgroundColor: COLORS.primary, padding: 16, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  detailBtnPrimaryText: { color: COLORS.bg, fontSize: 14, fontWeight: 'bold' },
  
  emptyText: { textAlign: 'center', marginTop: 20, marginBottom: 20, color: COLORS.textSub, fontSize: 14, fontStyle: 'italic' },
  
  bottomNav: { 
    flexDirection: 'row', 
    backgroundColor: '#0F0F12', 
    marginHorizontal: 15,
    marginBottom: 10,
    borderRadius: 24,
    height: 65, 
    alignItems: 'center', 
    justifyContent: 'space-around', 
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 20
  },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navItemCenterWrapper: {
    marginTop: -35,
    backgroundColor: '#0F0F12', 
    borderRadius: 40,
    padding: 6,
  },
  navItemCenter: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#1A1A1E', justifyContent: 'center', alignItems: 'center' },
  navItemCenterInner: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#839DD6', justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: '#A883D6' },
  navText: { color: '#8A8A9A', fontSize: 10, fontWeight: '700', marginTop: 4 },
  
  modalBox: { backgroundColor: COLORS.surface, padding: 25, paddingTop: 5, paddingBottom: 40, borderTopLeftRadius: 30, borderTopRightRadius: 30, zIndex: 2 },
  modalTitle: { color: COLORS.textMain, fontSize: 20, fontWeight: '900', marginBottom: 20 },
  modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  input: { backgroundColor: COLORS.bg, color: COLORS.textMain, padding: 16, borderRadius: 16, marginBottom: 15, fontSize: 16, borderWidth: 1, borderColor: COLORS.border },
  
  segmentedControl: { flexDirection: 'row', backgroundColor: COLORS.surfaceHigh, borderRadius: 20, padding: 4, marginBottom: 20 },
  segmentBtn: { flex: 1, paddingVertical: 12, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  segmentBtnActive: { backgroundColor: COLORS.primary, elevation: 2, shadowColor: '#000', shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.2, shadowRadius: 3 },
  segmentText: { color: COLORS.textSub, fontSize: 14, fontWeight: 'bold' },
  segmentTextActive: { color: COLORS.bg, fontWeight: '900' },

  searchModalBox: { backgroundColor: COLORS.surface, height: '90%', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 25, paddingTop: 5, zIndex: 2 },
  categoryScroll: { height: 50, marginBottom: 20 },
  pillBtn: { backgroundColor: COLORS.bg, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, borderWidth: 1, borderColor: COLORS.border, marginRight: 10, height: 40, justifyContent: 'center' },
  pillBtnActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  pillBtnText: { color: COLORS.textSub, fontSize: 13, fontWeight: 'bold' },
  searchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.bg, borderRadius: 16, paddingHorizontal: 15, borderWidth: 1, borderColor: COLORS.border, marginBottom: 15, height: 55 },
  searchInput: { flex: 1, color: COLORS.textMain, fontSize: 16, height: '100%' },
  searchResultItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  resultSymbol: { color: COLORS.textMain, fontSize: 16, fontWeight: 'bold' },
  resultName: { color: COLORS.textSub, fontSize: 12, marginTop: 2 },
  selectedAssetCard: { backgroundColor: COLORS.bg, padding: 15, borderRadius: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: COLORS.primary },
  selectedSymbol: { color: COLORS.primary, fontSize: 18, fontWeight: '900' },
  changeAssetBtn: { padding: 10, backgroundColor: COLORS.surfaceHigh, borderRadius: 12 },
  inputLabel: { color: COLORS.textSub, fontSize: 12, fontWeight: 'bold', marginBottom: 8, textTransform: 'uppercase' },
  modernInput: { backgroundColor: COLORS.bg, color: COLORS.textMain, padding: 15, borderRadius: 16, fontSize: 16, borderWidth: 1, borderColor: COLORS.border },
  megaSaveBtn: { backgroundColor: COLORS.primary, paddingVertical: 18, borderRadius: 16, alignItems: 'center', marginTop: 30 },
  megaSaveBtnText: { color: COLORS.bg, fontSize: 16, fontWeight: '900', letterSpacing: 1 },

  smartInputContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 15, marginBottom: 10 },
  smartInputCurrency: { color: COLORS.textSub, fontSize: 28, fontWeight: 'bold', marginHorizontal: 10 },
  smartInput: { color: COLORS.textMain, fontSize: 48, fontWeight: '900', minWidth: 100, textAlign: 'center', padding: 0 },
  smartFeedbackBox: { backgroundColor: COLORS.primarySoft, paddingVertical: 10, paddingHorizontal: 15, borderRadius: 12, flexDirection: 'row', alignItems: 'center', alignSelf: 'center', marginBottom: 20 },
  smartFeedbackText: { color: COLORS.primary, fontSize: 14, fontWeight: 'bold' },

  gridCard: { flex: 1, backgroundColor: '#16161A', margin: 6, borderRadius: 16, padding: 14, alignItems: 'flex-start', borderWidth: 1, borderColor: '#2A2A35' },
  gridSymbol: { color: '#FFFFFF', fontSize: 13, fontWeight: 'bold', marginBottom: 8 },
  gridPrice: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold', marginBottom: 12 },
  gridChange: { fontSize: 12, fontWeight: '600' },
  gridCardEditMode: { borderWidth: 1.5, borderColor: COLORS.error },
  gridName: { color: COLORS.textMain, fontSize: 14, fontWeight: 'bold' },
  gridPriceContainer: { alignItems: 'flex-start' },
  gridPricePrefix: { color: COLORS.textSub, fontSize: 10, fontWeight: 'bold', marginBottom: 2 },
  gridPrice: { color: COLORS.textMain, fontSize: 18, fontWeight: '900' },
  gridChangeContainer: { flexDirection: 'row', alignItems: 'center' },
  gridChangePct: { fontSize: 12, fontWeight: 'bold', marginLeft: 2 },
  deleteBadge: { position: 'absolute', top: -6, right: -6, width: 22, height: 22, borderRadius: 11, backgroundColor: COLORS.error, justifyContent: 'center', alignItems: 'center', zIndex: 10, borderWidth: 2, borderColor: COLORS.bg },
  doneBtn: { backgroundColor: COLORS.surfaceHigh, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  doneBtnText: { color: COLORS.primary, fontSize: 12, fontWeight: 'bold' },
  emptyMarketContainer: { alignItems: 'center', justifyContent: 'center', marginTop: 60, paddingHorizontal: 40 },
  emptyMarketText: { color: COLORS.textSub, fontSize: 14, textAlign: 'center', lineHeight: 22 },

  // YENİ: Güncellenmiş Özel Liste Satır Stilleri
  listOverviewContainer: { flex: 1, paddingHorizontal: 25 },
  listRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: COLORS.border },
  listRowName: { color: COLORS.textMain, fontSize: 16, fontWeight: 'normal', flex: 1 },
  listRowPill: { backgroundColor: COLORS.surfaceHigh, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, marginRight: 10 },
  listRowCount: { color: COLORS.textSub, fontSize: 12, fontWeight: 'bold' },
  listDetailHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, marginBottom: 20 },
  listDetailTitle: { color: COLORS.textMain, fontSize: 24, fontWeight: '900', marginLeft: 10 },

  // List Options Modal Styles
  optionsModalBox: { backgroundColor: COLORS.surface, padding: 25, paddingTop: 10, paddingBottom: 40, borderTopLeftRadius: 30, borderTopRightRadius: 30 },
  optionsHeader: { marginBottom: 25, alignItems: 'center' },
  optionsTitle: { color: COLORS.textMain, fontSize: 20, fontWeight: '900', marginBottom: 4 },
  optionsSub: { color: COLORS.textSub, fontSize: 13, textTransform: 'uppercase', letterSpacing: 1 },
  optionsList: { backgroundColor: COLORS.bg, borderRadius: 20, overflow: 'hidden', marginBottom: 25, borderWidth: 1, borderColor: COLORS.border },
  optionItem: { flexDirection: 'row', alignItems: 'center', padding: 18, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  optionIconBox: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  optionText: { color: COLORS.textMain, fontSize: 16, fontWeight: '600', flex: 1 },
  optionsCancelBtn: { backgroundColor: COLORS.surfaceHigh, paddingVertical: 16, borderRadius: 16, alignItems: 'center' },
  optionsCancelText: { color: COLORS.textMain, fontSize: 15, fontWeight: 'bold' },
  
  // YENİ: Boş Durum Yönlendirici Buton Stili
  ghostBtn: { marginTop: 20, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 20, backgroundColor: COLORS.surfaceHigh },
  ghostBtnText: { color: COLORS.primary, fontWeight: 'bold' }
});

